name: main workflow
on: push
defaults:
  run:
    working-directory: ../citest
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
    - run: find / -name Makefile
    - run: make install
    - run: make test
