name: main workflow
on: push
defaults:
  run:
    working-directory: ../citest
jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
    - run: ls -lha ../citest
    - run: make install
    - run: make test
